<?php

namespace Nitg\NitgTranslate\Providers;

use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Support\ServiceProvider;
use Nitg\NitgTranslate\Controllers\TranslateExportController;

class NitgTranslateProvider extends ServiceProvider
{
    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        $this->loadRoutesFrom(__DIR__.'/../../routes/api.php');
        $this->loadMigrationsFrom(__DIR__.'/../../migrations/create_translates_table.php');
        $this->publishes([
            __DIR__.'/../config/nitg-translate.php' => config_path('nitg-translate.php'),
        ], 'config');

        Relation::enforceMorphMap(
            array_combine(TranslateExportController::getTranslatableModels()->toArray(), TranslateExportController::getTranslatableModels()->toArray())
        );
    }
}
